pipeline {
    agent any
    
    tools {
        maven 'maven-3.9.5'
        dockerTool 'docker'
    }

    stages {
        stage('Build') {
            steps {
                git branch: 'master', credentialsId: '0b032dba-961b-4dd1-8100-f602249e84f4', url: 'https://github.com/ksmehara/basic-app.git'
                sh 'mvn clean compile'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
		
		stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        
        stage('Deploy') {
            steps {
			    sh 'mvn jar:jar install:install help:evaluate -Dexpression=project.name'
                sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
            }
        }
    }
}
